"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deleteVariant = exports.updateVariant = exports.getAllVariants = exports.getVariant = exports.createVariant = void 0;
const VariantModel_1 = require("../models/VariantModel");
const factoryController_1 = require("./factoryController");
exports.createVariant = (0, factoryController_1.createEntitiy)(VariantModel_1.Variant);
exports.getVariant = (0, factoryController_1.getEntitiy)(VariantModel_1.Variant);
exports.getAllVariants = (0, factoryController_1.getAllEntitiy)(VariantModel_1.Variant);
exports.updateVariant = (0, factoryController_1.updateEntitiy)(VariantModel_1.Variant);
exports.deleteVariant = (0, factoryController_1.deleteEntitiy)(VariantModel_1.Variant);
